-- WARNING: This schema is for context only and is not meant to be run.
-- It is a faithful snapshot (DDL form) of the reactstudio-owned tables that live in the SHARED Supabase
-- alongside totalmanagements (ERP). The full ERP schema lives in `totalmanagements/schema_.sql`.
-- Generated from information_schema / pg_indexes via Supabase MCP.
-- Tables here: inquiries, quotes, contracts, agreements, react_staff_* + the reactstudio-extended
-- columns of public.financial_entries (which is shared with the ERP).
--
-- Why this file exists:
--  * The ERP repo's schema_.sql does not declare these tables, so the canonical "shape of one DB"
--    cannot be reconstructed from totalmanagements alone.
--  * The ERP type FinancialEntry.project_id is declared NOT NULL but the actual column is nullable.
--    This file documents the actual, current state so the two repos can stay in sync.
--
-- Conventions:
--  * `bu_code` is the public.bu_code enum (defined in the ERP DB), default 'REACT' for these tables.
--  * `agreements.bu_code` is currently `text` (NOT the bu_code enum) — see "Known divergences" below.
--  * All FKs and indexes reflect what exists in the live DB at the time of dumping.

-- =====================================================================
-- inquiries  (REACT BU lead intake)
-- =====================================================================
CREATE TABLE public.inquiries (
  id                bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bu_code           public.bu_code NOT NULL DEFAULT 'REACT'::public.bu_code,
  name              text NOT NULL,
  email             text NOT NULL,
  phone             text NOT NULL,
  company           text,
  services          text[] DEFAULT '{}'::text[],
  project_title     text,
  project_scale     text,
  deadline          text,
  budget_range      text,
  description       text,
  reference_url     text,
  reference_urls    jsonb DEFAULT '[]'::jsonb,
  message           text,
  intake_payload    jsonb NOT NULL DEFAULT '{}'::jsonb, -- structured wizard payload (phase 2)
  status            text NOT NULL DEFAULT 'new'::text,
  client_token      uuid UNIQUE DEFAULT gen_random_uuid(),
  project_id        bigint, -- soft link to public.projects(id); NOT enforced as FK in current DB
  partner_id        bigint, -- phase 3: optional FK to public.partners(id) ON DELETE SET NULL
  created_at        timestamptz DEFAULT now(),
  CONSTRAINT inquiries_pkey PRIMARY KEY (id),
  CONSTRAINT inquiries_partner_id_fkey FOREIGN KEY (partner_id)
    REFERENCES public.partners(id) ON DELETE SET NULL
);
CREATE INDEX idx_inquiries_bu_code     ON public.inquiries (bu_code);
CREATE INDEX idx_inquiries_client_token ON public.inquiries (client_token);
CREATE INDEX idx_inquiries_created_at  ON public.inquiries (created_at DESC);
CREATE INDEX idx_inquiries_status      ON public.inquiries (status);
CREATE INDEX inquiries_partner_id_idx  ON public.inquiries (partner_id) WHERE partner_id IS NOT NULL;

-- =====================================================================
-- quotes  (REACT BU sales pipeline)
-- =====================================================================
CREATE TABLE public.quotes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bu_code               public.bu_code NOT NULL DEFAULT 'REACT'::public.bu_code,
  inquiry_id            bigint NOT NULL,
  items                 jsonb NOT NULL DEFAULT '[]'::jsonb,
  supply_amount         bigint DEFAULT 0,
  vat                   bigint DEFAULT 0,
  total_amount          bigint DEFAULT 0,
  valid_until           date,
  notes                 text,
  status                text NOT NULL DEFAULT 'draft'::text,
  sent_at               timestamptz,
  view_token            uuid UNIQUE DEFAULT gen_random_uuid(),
  client_response       text,
  client_response_at    timestamptz,
  client_response_note  text,
  created_at            timestamptz DEFAULT now(),
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_inquiry_id_fkey FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id)
);
CREATE INDEX idx_quotes_bu_code    ON public.quotes (bu_code);
CREATE INDEX idx_quotes_inquiry_id ON public.quotes (inquiry_id);
CREATE INDEX idx_quotes_status     ON public.quotes (status);
CREATE INDEX idx_quotes_view_token ON public.quotes (view_token);

-- =====================================================================
-- contracts  (REACT BU contract documents)
-- =====================================================================
CREATE TABLE public.contracts (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bu_code                 public.bu_code NOT NULL DEFAULT 'REACT'::public.bu_code,
  inquiry_id              bigint,
  quote_id                bigint,
  project_id              bigint, -- soft link to public.projects(id); NOT enforced as FK
  title                   text NOT NULL,
  contract_type           text NOT NULL DEFAULT 'service'::text,
  client_name             text NOT NULL,
  client_email            text NOT NULL,
  client_phone            text,
  client_company          text,
  items                   jsonb DEFAULT '[]'::jsonb,
  supply_amount           bigint DEFAULT 0,
  vat                     bigint DEFAULT 0,
  total_amount            bigint DEFAULT 0,
  deposit_amount          bigint DEFAULT 0,
  deposit_due_date        date,
  balance_amount          bigint DEFAULT 0,
  balance_due_date        date,
  start_date              date,
  end_date                date,
  terms                   text,
  status                  text NOT NULL DEFAULT 'draft'::text,
  sign_token              uuid UNIQUE DEFAULT gen_random_uuid(),
  client_signature_data   text,
  client_signed_at        timestamptz,
  company_signature_data  text,
  sent_at                 timestamptz,
  created_at              timestamptz DEFAULT now(),
  updated_at              timestamptz DEFAULT now(),
  CONSTRAINT contracts_pkey PRIMARY KEY (id),
  CONSTRAINT contracts_inquiry_id_fkey FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id),
  CONSTRAINT contracts_quote_id_fkey   FOREIGN KEY (quote_id)   REFERENCES public.quotes(id)
);
CREATE INDEX idx_contracts_bu_code    ON public.contracts (bu_code);
CREATE INDEX idx_contracts_inquiry_id ON public.contracts (inquiry_id);
CREATE INDEX idx_contracts_sign_token ON public.contracts (sign_token);
CREATE INDEX idx_contracts_status     ON public.contracts (status);

-- =====================================================================
-- agreements  (REACT BU short-form production agreement template)
--   NOTE: bu_code here is `text`, NOT the public.bu_code enum used by other tables.
-- =====================================================================
CREATE TABLE public.agreements (
  id                     bigint NOT NULL DEFAULT nextval('public.agreements_id_seq'::regclass),
  bu_code                text NOT NULL DEFAULT 'REACT'::text, -- divergence from enum-based bu_code
  inquiry_id             bigint, -- not a DB-level FK currently
  quote_id               bigint, -- not a DB-level FK currently
  title                  text NOT NULL,
  client_company         text NOT NULL DEFAULT ''::text,
  client_address         text DEFAULT ''::text,
  client_representative  text DEFAULT ''::text,
  client_email           text DEFAULT ''::text,
  client_phone           text DEFAULT ''::text,
  task_description       text DEFAULT ''::text,
  deliverables           text DEFAULT '편집이 완료된 최종 마스터 파일 1종'::text,
  shooting_date          date,
  delivery_date          date,
  release_date           date,
  total_amount           numeric NOT NULL DEFAULT 0,
  vat_type               text NOT NULL DEFAULT 'exclusive'::text,
  deposit_rate           integer NOT NULL DEFAULT 20,
  deposit_amount         numeric NOT NULL DEFAULT 0,
  balance_rate           integer NOT NULL DEFAULT 80,
  balance_amount         numeric NOT NULL DEFAULT 0,
  deposit_condition      text DEFAULT '계약 체결 후 7일 이내 지급'::text,
  balance_condition      text DEFAULT '릴리즈 예정일로부터 30일 이내 지급'::text,
  free_revision_count    integer NOT NULL DEFAULT 2,
  penalty_rates          jsonb NOT NULL DEFAULT
    '[{"rate": 30, "label": "계약 체결 후 ~ 촬영 7일 전"},
      {"rate": 50, "label": "촬영 예정일 기준 7일 이내"},
      {"rate": 100, "label": "촬영 완료 이후"}]'::jsonb,
  contract_date          date,
  status                 text NOT NULL DEFAULT 'draft'::text,
  sent_at                timestamptz,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agreements_pkey PRIMARY KEY (id)
);

-- =====================================================================
-- react_staff_*  (REACT BU staff pool intake and admin CRM)
-- =====================================================================
CREATE TABLE public.react_staff_applications (
  id                            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bu_code                       public.bu_code NOT NULL DEFAULT 'REACT'::public.bu_code,
  applicant_type                text NOT NULL CHECK (applicant_type IN ('company', 'team', 'individual')),
  status                        text NOT NULL DEFAULT 'new'::text CHECK (status IN ('new', 'reviewing', 'shortlisted', 'approved', 'archived', 'rejected')),
  display_name                  text NOT NULL,
  legal_name                    text,
  company_name                  text,
  representative_name           text,
  contact_name                  text,
  phone                         text NOT NULL,
  email                         text NOT NULL,
  birth_date                    date,
  business_registration_number  text,
  opened_on                     date,
  region                        text,
  website_url                   text,
  social_links                  jsonb NOT NULL DEFAULT '[]'::jsonb,
  portfolio_urls                jsonb NOT NULL DEFAULT '[]'::jsonb,
  summary                       text,
  availability                  text,
  preferred_project_types       text[] NOT NULL DEFAULT '{}'::text[],
  equipment                     text[] NOT NULL DEFAULT '{}'::text[],
  equipment_detail              text,
  tools                         text[] NOT NULL DEFAULT '{}'::text[],
  ai_tools                      text[] NOT NULL DEFAULT '{}'::text[],
  capability_tags               text[] NOT NULL DEFAULT '{}'::text[],
  raw_payload                   jsonb NOT NULL DEFAULT '{}'::jsonb,
  admin_rating                  integer CHECK (admin_rating IS NULL OR (admin_rating >= 1 AND admin_rating <= 5)),
  partner_id                    bigint REFERENCES public.partners(id) ON DELETE SET NULL,
  created_partner_at            timestamptz,
  reviewed_by                   uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  reviewed_at                   timestamptz,
  created_at                    timestamptz NOT NULL DEFAULT now(),
  updated_at                    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT react_staff_applications_pkey PRIMARY KEY (id)
);
CREATE INDEX react_staff_applications_bu_status_idx
  ON public.react_staff_applications (bu_code, status, created_at DESC);
CREATE INDEX react_staff_applications_type_idx
  ON public.react_staff_applications (applicant_type);
CREATE INDEX react_staff_applications_capability_tags_idx
  ON public.react_staff_applications USING gin (capability_tags);
CREATE INDEX react_staff_applications_tools_idx
  ON public.react_staff_applications USING gin (tools);
CREATE INDEX react_staff_applications_equipment_idx
  ON public.react_staff_applications USING gin (equipment);

CREATE TABLE public.react_staff_capabilities (
  id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  application_id   bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  category         text NOT NULL,
  proficiency      text CHECK (proficiency IS NULL OR proficiency IN ('assist', 'working', 'lead', 'specialist')),
  role_detail      text,
  portfolio_urls   jsonb NOT NULL DEFAULT '[]'::jsonb,
  tools            text[] NOT NULL DEFAULT '{}'::text[],
  equipment        text[] NOT NULL DEFAULT '{}'::text[],
  notes            text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT react_staff_capabilities_pkey PRIMARY KEY (id)
);
CREATE INDEX react_staff_capabilities_application_idx
  ON public.react_staff_capabilities (application_id);
CREATE INDEX react_staff_capabilities_category_idx
  ON public.react_staff_capabilities (category);

CREATE TABLE public.react_staff_skill_entries (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  application_id           bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  skill_group              text NOT NULL,
  skill_name               text NOT NULL,
  experience_level         text CHECK (experience_level IS NULL OR experience_level IN ('junior', 'mid', 'senior', 'lead', 'specialist')),
  years_experience         numeric(4, 1),
  role_detail              text,
  representative_work_url  text,
  tools                    text[] NOT NULL DEFAULT '{}'::text[],
  equipment                text[] NOT NULL DEFAULT '{}'::text[],
  notes                    text,
  created_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT react_staff_skill_entries_pkey PRIMARY KEY (id)
);
CREATE INDEX react_staff_skill_entries_application_idx
  ON public.react_staff_skill_entries (application_id);
CREATE INDEX react_staff_skill_entries_group_skill_idx
  ON public.react_staff_skill_entries (skill_group, skill_name);
CREATE INDEX react_staff_skill_entries_tools_idx
  ON public.react_staff_skill_entries USING gin (tools);
CREATE INDEX react_staff_skill_entries_equipment_idx
  ON public.react_staff_skill_entries USING gin (equipment);

CREATE TABLE public.react_staff_rate_cards (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  application_id      bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  skill_group         text NOT NULL,
  skill_name          text,
  rate_unit           text NOT NULL DEFAULT 'per_day'::text CHECK (rate_unit IN ('per_day', 'per_half_day', 'per_project', 'per_video', 'per_hour', 'monthly', 'negotiable')),
  currency            text NOT NULL DEFAULT 'KRW'::text,
  min_amount          numeric,
  max_amount          numeric,
  is_negotiable       boolean NOT NULL DEFAULT true,
  includes_equipment  boolean NOT NULL DEFAULT false,
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT react_staff_rate_cards_pkey PRIMARY KEY (id)
);
CREATE INDEX react_staff_rate_cards_application_idx
  ON public.react_staff_rate_cards (application_id);
CREATE INDEX react_staff_rate_cards_group_idx
  ON public.react_staff_rate_cards (skill_group, rate_unit);
CREATE INDEX react_staff_rate_cards_amount_idx
  ON public.react_staff_rate_cards (min_amount, max_amount);

CREATE TABLE public.react_staff_files (
  id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  application_id   bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  document_type    text NOT NULL,
  bucket           text NOT NULL DEFAULT 'react-staff-files'::text,
  object_path      text NOT NULL,
  file_name        text NOT NULL,
  mime_type        text,
  size_bytes       bigint,
  uploaded_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT react_staff_files_pkey PRIMARY KEY (id),
  CONSTRAINT react_staff_files_bucket_object_path_key UNIQUE (bucket, object_path)
);
CREATE INDEX react_staff_files_application_idx
  ON public.react_staff_files (application_id);

CREATE TABLE public.react_staff_notes (
  id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  application_id  bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  note            text NOT NULL,
  created_by      uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT react_staff_notes_pkey PRIMARY KEY (id)
);
CREATE INDEX react_staff_notes_application_idx
  ON public.react_staff_notes (application_id, created_at DESC);

-- =====================================================================
-- financial_entries  (SHARED with the ERP totalmanagements)
--   * The full table is defined in the ERP schema; only divergences
--     from totalmanagements/schema_.sql are documented below.
--   * Reactstudio writes here with bu_code='REACT' only (see ADMIN_BU in
--     reactstudio/lib/admin-auth.ts).
-- =====================================================================
-- Divergence #1: project_id is NULLable in the live DB (the ERP snapshot says NOT NULL).
-- Divergence #2: the following columns exist in the live DB but are absent from totalmanagements/schema_.sql:
--   contract_id        bigint        REFERENCES public.contracts(id)
--   client_name        text
--   due_date           date
--   paid_at            timestamptz
--   payee_app_user_id  uuid          REFERENCES public.app_users(id)
--   approved_by        uuid          REFERENCES public.app_users(id)
--   approved_at        timestamptz
--   payment_ref        text
--
-- Indexes (live DB) related to reactstudio usage:
CREATE INDEX        financial_entries_contract_idx
  ON public.financial_entries (contract_id) WHERE (contract_id IS NOT NULL);
CREATE UNIQUE INDEX financial_entries_contract_installment_uq
  ON public.financial_entries (contract_id, category)
  WHERE (kind = 'revenue'::public.financial_kind
         AND contract_id IS NOT NULL
         AND status <> 'canceled'::public.financial_status
         AND category = ANY (ARRAY['deposit'::text, 'balance'::text]));
CREATE INDEX        financial_entries_kind_bu_due_idx
  ON public.financial_entries (kind, bu_code, due_date);
CREATE INDEX        idx_fe_due_date
  ON public.financial_entries (due_date) WHERE (kind = 'expense'::public.financial_kind);
CREATE INDEX        idx_fe_payee_app_user
  ON public.financial_entries (payee_app_user_id) WHERE (payee_app_user_id IS NOT NULL);

-- =====================================================================
-- Known divergences vs totalmanagements/schema_.sql
-- =====================================================================
-- 1. financial_entries.project_id : ERP snapshot says NOT NULL, live DB is nullable.
--    -> See planned phase 1: relax ERP snapshot + ERP TS type to match.
-- 2. financial_entries.{contract_id, client_name, due_date, paid_at, payee_app_user_id,
--                       approved_by, approved_at, payment_ref}
--    are absent from the ERP snapshot but present in the live DB.
--    The ERP API does not select/insert these columns, so this divergence is informational only.
-- 3. agreements.bu_code is `text`, not the public.bu_code enum used by every other table.
--    Consider migrating to the enum in a future maintenance pass (NOT in scope of phases 0-3).
