-- REACT staff pool intake and admin CRM.
-- Non-destructive: creates new REACT-owned tables and a private storage bucket.

CREATE TABLE IF NOT EXISTS public.react_staff_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bu_code public.bu_code NOT NULL DEFAULT 'REACT'::public.bu_code,
  applicant_type text NOT NULL CHECK (applicant_type IN ('company', 'team', 'individual')),
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'reviewing', 'shortlisted', 'approved', 'archived', 'rejected')),
  display_name text NOT NULL,
  legal_name text,
  company_name text,
  representative_name text,
  contact_name text,
  phone text NOT NULL,
  email text NOT NULL,
  birth_date date,
  business_registration_number text,
  opened_on date,
  region text,
  website_url text,
  social_links jsonb NOT NULL DEFAULT '[]'::jsonb,
  portfolio_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
  summary text,
  availability text,
  preferred_project_types text[] NOT NULL DEFAULT '{}'::text[],
  equipment text[] NOT NULL DEFAULT '{}'::text[],
  tools text[] NOT NULL DEFAULT '{}'::text[],
  ai_tools text[] NOT NULL DEFAULT '{}'::text[],
  capability_tags text[] NOT NULL DEFAULT '{}'::text[],
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  admin_rating integer CHECK (admin_rating IS NULL OR (admin_rating >= 1 AND admin_rating <= 5)),
  partner_id bigint REFERENCES public.partners(id) ON DELETE SET NULL,
  created_partner_at timestamptz,
  reviewed_by uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_staff_applications_bu_status_idx
  ON public.react_staff_applications (bu_code, status, created_at DESC);
CREATE INDEX IF NOT EXISTS react_staff_applications_type_idx
  ON public.react_staff_applications (applicant_type);
CREATE INDEX IF NOT EXISTS react_staff_applications_capability_tags_idx
  ON public.react_staff_applications USING gin (capability_tags);
CREATE INDEX IF NOT EXISTS react_staff_applications_tools_idx
  ON public.react_staff_applications USING gin (tools);
CREATE INDEX IF NOT EXISTS react_staff_applications_equipment_idx
  ON public.react_staff_applications USING gin (equipment);

CREATE TABLE IF NOT EXISTS public.react_staff_capabilities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  category text NOT NULL,
  proficiency text CHECK (proficiency IS NULL OR proficiency IN ('assist', 'working', 'lead', 'specialist')),
  role_detail text,
  portfolio_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
  tools text[] NOT NULL DEFAULT '{}'::text[],
  equipment text[] NOT NULL DEFAULT '{}'::text[],
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_staff_capabilities_application_idx
  ON public.react_staff_capabilities (application_id);
CREATE INDEX IF NOT EXISTS react_staff_capabilities_category_idx
  ON public.react_staff_capabilities (category);

CREATE TABLE IF NOT EXISTS public.react_staff_skill_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  skill_group text NOT NULL,
  skill_name text NOT NULL,
  experience_level text CHECK (experience_level IS NULL OR experience_level IN ('junior', 'mid', 'senior', 'lead', 'specialist')),
  years_experience numeric(4, 1),
  role_detail text,
  representative_work_url text,
  tools text[] NOT NULL DEFAULT '{}'::text[],
  equipment text[] NOT NULL DEFAULT '{}'::text[],
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_staff_skill_entries_application_idx
  ON public.react_staff_skill_entries (application_id);
CREATE INDEX IF NOT EXISTS react_staff_skill_entries_group_skill_idx
  ON public.react_staff_skill_entries (skill_group, skill_name);
CREATE INDEX IF NOT EXISTS react_staff_skill_entries_tools_idx
  ON public.react_staff_skill_entries USING gin (tools);
CREATE INDEX IF NOT EXISTS react_staff_skill_entries_equipment_idx
  ON public.react_staff_skill_entries USING gin (equipment);

CREATE TABLE IF NOT EXISTS public.react_staff_rate_cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  skill_group text NOT NULL,
  skill_name text,
  rate_unit text NOT NULL DEFAULT 'per_day' CHECK (rate_unit IN ('per_day', 'per_half_day', 'per_project', 'per_video', 'per_hour', 'monthly', 'negotiable')),
  currency text NOT NULL DEFAULT 'KRW',
  min_amount numeric,
  max_amount numeric,
  is_negotiable boolean NOT NULL DEFAULT true,
  includes_equipment boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_staff_rate_cards_application_idx
  ON public.react_staff_rate_cards (application_id);
CREATE INDEX IF NOT EXISTS react_staff_rate_cards_group_idx
  ON public.react_staff_rate_cards (skill_group, rate_unit);
CREATE INDEX IF NOT EXISTS react_staff_rate_cards_amount_idx
  ON public.react_staff_rate_cards (min_amount, max_amount);

CREATE TABLE IF NOT EXISTS public.react_staff_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  document_type text NOT NULL,
  bucket text NOT NULL DEFAULT 'react-staff-files',
  object_path text NOT NULL,
  file_name text NOT NULL,
  mime_type text,
  size_bytes bigint,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (bucket, object_path)
);

CREATE INDEX IF NOT EXISTS react_staff_files_application_idx
  ON public.react_staff_files (application_id);

CREATE TABLE IF NOT EXISTS public.react_staff_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL REFERENCES public.react_staff_applications(id) ON DELETE CASCADE,
  note text NOT NULL,
  created_by uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_staff_notes_application_idx
  ON public.react_staff_notes (application_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.react_staff_touch_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS react_staff_applications_touch_updated_at
  ON public.react_staff_applications;
CREATE TRIGGER react_staff_applications_touch_updated_at
BEFORE UPDATE ON public.react_staff_applications
FOR EACH ROW
EXECUTE FUNCTION public.react_staff_touch_updated_at();

ALTER TABLE public.react_staff_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_staff_capabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_staff_skill_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_staff_rate_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_staff_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_staff_notes ENABLE ROW LEVEL SECURITY;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'react-staff-files',
  'react-staff-files',
  false,
  10485760,
  ARRAY[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]::text[]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

COMMENT ON TABLE public.react_staff_applications IS
  'REACT Studio staff pool applications from companies, teams, and individuals.';
COMMENT ON TABLE public.react_staff_skill_entries IS
  'Detailed skill evidence for staff pool filtering, such as gimbal, jimmy jib, OAP, live streaming, and subtitle design.';
COMMENT ON TABLE public.react_staff_rate_cards IS
  'Applicant-provided rate cards by skill and unit, used for rough filtering only.';
