-- REACT review rooms for video feedback and client/editor collaboration.
-- Non-destructive: creates REACT-owned review tables accessed through server APIs.

CREATE TABLE IF NOT EXISTS public.react_review_rooms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bu_code public.bu_code NOT NULL DEFAULT 'REACT'::public.bu_code,
  project_id bigint REFERENCES public.projects(id) ON DELETE SET NULL,
  title text NOT NULL,
  client_name text,
  description text,
  share_token text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'uploading', 'processing', 'open', 'in_review', 'approved', 'archived')),
  default_privacy text NOT NULL DEFAULT 'unlisted'
    CHECK (default_privacy IN ('private', 'unlisted')),
  expires_at timestamptz,
  last_viewed_at timestamptz,
  created_by uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_review_rooms_bu_status_idx
  ON public.react_review_rooms (bu_code, status, created_at DESC);

CREATE INDEX IF NOT EXISTS react_review_rooms_project_idx
  ON public.react_review_rooms (project_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.react_review_videos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id bigint NOT NULL REFERENCES public.react_review_rooms(id) ON DELETE CASCADE,
  version_label text NOT NULL DEFAULT 'v1',
  title text NOT NULL,
  description text,
  youtube_video_id text,
  youtube_url text,
  thumbnail_url text,
  file_name text,
  mime_type text,
  size_bytes bigint,
  upload_status text NOT NULL DEFAULT 'queued'
    CHECK (upload_status IN ('queued', 'uploading', 'processing', 'ready', 'failed')),
  youtube_response jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_current boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS react_review_videos_one_current_idx
  ON public.react_review_videos (room_id)
  WHERE is_current;

CREATE INDEX IF NOT EXISTS react_review_videos_room_idx
  ON public.react_review_videos (room_id, created_at DESC);

CREATE INDEX IF NOT EXISTS react_review_videos_youtube_idx
  ON public.react_review_videos (youtube_video_id)
  WHERE youtube_video_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.react_review_annotations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id bigint NOT NULL REFERENCES public.react_review_rooms(id) ON DELETE CASCADE,
  video_id bigint NOT NULL REFERENCES public.react_review_videos(id) ON DELETE CASCADE,
  body text NOT NULL,
  time_sec numeric(10, 3) NOT NULL DEFAULT 0,
  x_pct numeric(6, 3),
  y_pct numeric(6, 3),
  w_pct numeric(6, 3),
  h_pct numeric(6, 3),
  shape text NOT NULL DEFAULT 'time'
    CHECK (shape IN ('time', 'pin', 'box')),
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'in_progress', 'resolved', 'approved')),
  priority text NOT NULL DEFAULT 'normal'
    CHECK (priority IN ('normal', 'high')),
  author_name text NOT NULL,
  author_email text,
  author_role text NOT NULL DEFAULT 'client'
    CHECK (author_role IN ('internal', 'client', 'channel_owner', 'editor', 'director', 'viewer')),
  created_by uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  assigned_to uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  resolved_by uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_review_annotations_room_status_idx
  ON public.react_review_annotations (room_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS react_review_annotations_video_time_idx
  ON public.react_review_annotations (video_id, time_sec);

CREATE TABLE IF NOT EXISTS public.react_review_replies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  annotation_id bigint NOT NULL REFERENCES public.react_review_annotations(id) ON DELETE CASCADE,
  body text NOT NULL,
  author_name text NOT NULL,
  author_email text,
  author_role text NOT NULL DEFAULT 'client'
    CHECK (author_role IN ('internal', 'client', 'channel_owner', 'editor', 'director', 'viewer')),
  created_by uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_review_replies_annotation_idx
  ON public.react_review_replies (annotation_id, created_at ASC);

CREATE TABLE IF NOT EXISTS public.react_review_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id bigint NOT NULL REFERENCES public.react_review_rooms(id) ON DELETE CASCADE,
  video_id bigint REFERENCES public.react_review_videos(id) ON DELETE CASCADE,
  annotation_id bigint REFERENCES public.react_review_annotations(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  actor_name text,
  actor_role text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS react_review_events_room_idx
  ON public.react_review_events (room_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.react_review_touch_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER react_review_rooms_touch_updated_at
BEFORE UPDATE ON public.react_review_rooms
FOR EACH ROW
EXECUTE FUNCTION public.react_review_touch_updated_at();

CREATE OR REPLACE TRIGGER react_review_videos_touch_updated_at
BEFORE UPDATE ON public.react_review_videos
FOR EACH ROW
EXECUTE FUNCTION public.react_review_touch_updated_at();

CREATE OR REPLACE TRIGGER react_review_annotations_touch_updated_at
BEFORE UPDATE ON public.react_review_annotations
FOR EACH ROW
EXECUTE FUNCTION public.react_review_touch_updated_at();

ALTER TABLE public.react_review_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_review_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_review_annotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_review_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.react_review_events ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.react_review_rooms IS
  'REACT Studio token-based video review rooms for internal, client, channel owner, editor, and director feedback.';

COMMENT ON TABLE public.react_review_annotations IS
  'Timed and screen-positioned video feedback stored in REACT DB instead of YouTube comments.';
