-- REACT staff availability poll links for the Ewha dance academy fixed director project.
-- Non-destructive: creates a token-based response table that can exist before a full staff application.

CREATE TABLE IF NOT EXISTS public.react_staff_availability_polls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bu_code public.bu_code NOT NULL DEFAULT 'REACT'::public.bu_code,
  application_id bigint REFERENCES public.react_staff_applications(id) ON DELETE SET NULL,
  token text NOT NULL UNIQUE,
  mailbox text,
  source_uid text,
  source_message_id text,
  source_subject text,
  invitee_name text,
  invitee_email text,
  invitee_phone text,
  project_key text NOT NULL DEFAULT 'mid_dance_school_weekly',
  project_title text NOT NULL DEFAULT '이대역 댄스학원 정기 영상 촬영·편집',
  candidate_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  age_signal text NOT NULL DEFAULT 'unknown'
    CHECK (age_signal IN ('target', 'maybe', 'unknown', 'out_of_range')),
  age_estimate integer CHECK (age_estimate IS NULL OR (age_estimate >= 14 AND age_estimate <= 80)),
  age_evidence text,
  response_status text NOT NULL DEFAULT 'pending'
    CHECK (response_status IN ('pending', 'available', 'maybe', 'unavailable')),
  available_days text[] NOT NULL DEFAULT '{}'::text[],
  preferred_time text,
  rate_note text,
  equipment_note text,
  message text,
  submitted_at timestamptz,
  last_viewed_at timestamptz,
  user_agent text,
  ip_hint text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS react_staff_availability_polls_source_uid_key
  ON public.react_staff_availability_polls (mailbox, source_uid)
  WHERE mailbox IS NOT NULL AND source_uid IS NOT NULL;

CREATE INDEX IF NOT EXISTS react_staff_availability_polls_application_idx
  ON public.react_staff_availability_polls (application_id, created_at DESC);

CREATE INDEX IF NOT EXISTS react_staff_availability_polls_project_status_idx
  ON public.react_staff_availability_polls (project_key, response_status, created_at DESC);

CREATE INDEX IF NOT EXISTS react_staff_availability_polls_email_idx
  ON public.react_staff_availability_polls (lower(invitee_email));

DROP TRIGGER IF EXISTS react_staff_availability_polls_touch_updated_at
  ON public.react_staff_availability_polls;
CREATE TRIGGER react_staff_availability_polls_touch_updated_at
BEFORE UPDATE ON public.react_staff_availability_polls
FOR EACH ROW
EXECUTE FUNCTION public.react_staff_touch_updated_at();

ALTER TABLE public.react_staff_availability_polls ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.react_staff_availability_polls IS
  'Token-based availability responses for REACT staff candidates, including internal-only age inference.';
COMMENT ON COLUMN public.react_staff_availability_polls.age_signal IS
  'Internal-only age fit signal inferred from inbound mail context. Do not expose to invitees.';
COMMENT ON COLUMN public.react_staff_availability_polls.candidate_snapshot IS
  'Inbound mail and draft context snapshot used for staff pool review and later prefill.';
